/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShuttleButton: typeof import('./src/components/ShuttleButton.vue')['default']
    ShuttleButtonAdd: typeof import('./src/components/ShuttleButtonAdd.vue')['default']
    ShuttleButtonAlert: typeof import('./src/components/ShuttleButtonAlert.vue')['default']
    ShuttleButtonEdit: typeof import('./src/components/ShuttleButtonEdit.vue')['default']
    ShuttleButtonUrl: typeof import('./src/components/ShuttleButtonUrl.vue')['default']
    ShuttleContainer: typeof import('./src/components/ShuttleContainer.vue')['default']
    ShuttleDataTable: typeof import('./src/components/ShuttleDataTable.vue')['default']
    ShuttleDrawer: typeof import('./src/components/ShuttleDrawer.vue')['default']
    ShuttleFilterDrawer: typeof import('./src/components/ShuttleFilterDrawer.vue')['default']
    ShuttleFilterToggle: typeof import('./src/components/ShuttleFilterToggle.vue')['default']
    ShuttleForm: typeof import('./src/components/ShuttleForm.vue')['default']
    ShuttleNavbar: typeof import('./src/components/ShuttleNavbar.vue')['default']
    ShuttleStrip: typeof import('./src/components/ShuttleStrip.vue')['default']
    ShuttleTitle: typeof import('./src/components/ShuttleTitle.vue')['default']
  }
}
